spring: 
   #数据库
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
      username: root
      password: 123456
