feign:
   hystrix:
      enabled: true

hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 125000
   threadpool:
      default:
         coreSize: 100

ribbon:
   ConnectTimeout: 1000
   ReadTimeout: 60000
   OkToRetryOnAllOperations: true
   MaxAutoRetriesNextServer: 1
   MaxAutoRetries: 0
   
zuul:
   ignoredServices: '*'
   routes:
      remexfastbuildertemplate-org-service:
         path: /remexfastbuildertemplate-org-service/**
      remexfastbuildertemplate-resources-service:
         path: /remexfastbuildertemplate-resources-service/**
      remexfastbuildertemplate-media-service:
         path: /remexfastbuildertemplate-media-service/**
